version: "3.9"

services:
  s3:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage/minio:/data
    environment:
      MINIO_ROOT_USER: username
      MINIO_ROOT_PASSWORD: password
    command: server --address 0.0.0.0:9000 --console-address 0.0.0.0:9001 /data
